name: Deploy

on:
    workflow_run:
        workflows: ["Push to Docker hub"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Delete Old docker container
              run: sudo docker rm -f ordernow-backend-container || true
            - name: Pull Docker image
              run: sudo docker pull yuankai619/keelungsightviewer:latest
            - name: Run Docker Container
              run: |
                  sudo docker run -d -p 8080:8080 \
                    -e DB_NAME='KeelungSightDB' \
                    -e DB_PASSWORD='passwordKEN930619' \
                    -e PORT='8080' \
                    --name keelungsightviewer-container \
                    yuankai619/keelungsightviewer:latest
