name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to the Docker Hub registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build \
            -t yuankai619/keelungsightviewer:latest .

      - name: Push the Docker image to Docker Hub
        run: docker push yuankai619/keelungsightviewer:latest

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "keelung-sight-viewer"
          heroku_email: "01157116@email.ntou.edu.tw"
          docker_image: "yuankai619/keelungsightviewer:latest"
          usedocker: true
          docker_heroku_process_type: web
          docker_build_args: |
            DB_PASSWORD
            DB_NAME
        env:
          DB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DB_NAME: ${{ secrets.DOCKER_USERNAME }}